source :rubygems

gem 'activerecord', '3.0.10'
gem 'jdbc-mysql'
gem 'activerecord-jdbcmysql-adapter'

group :development, :test do
  gem 'ruby-debug', :platforms => [:jruby, :ruby_18]
  gem 'ruby-debug19', :platforms => [:ruby_19]
end

group :development do
  gem 'mongrel', '~> 1.2.0.pre2'
end

group :test do
  gem 'factory_girl', '~> 1.3.3'
  gem 'shoulda', '~> 2.11.3'
  gem 'simplecov'
  gem 'spork', '~> 0.9.0.rc9'
end
