source 'https://rubygems.org'

ruby '2.0.0'

gem 'rails', '~> 3.2.17'
gem 'unicorn'
gem 'will_paginate', '~> 3.0.4'
gem 'mysql2', '~> 0.3.13'
gem 'newrelic_rpm'
gem 'json', '~> 1.7.7'
gem 'nokogiri', '~> 1.6.0'
gem 'pusher', '~> 0.11.3'
gem 'aws-sdk'
gem 'paperclip', '~> 3.5.0'
gem 'twilio', '~> 3.1.1'
gem 'settingslogic', '~> 2.0.9'
gem 'twilio-ruby', '~> 3.10.0'
gem 'dynamic_form', '~> 1.1.4'
gem 'jquery-rails', '~> 3.0.4'
gem 'activerecord-import', '~> 0.4.1'
gem 'recurly', '~> 2.1.9'
gem 'heroku'
gem 'uuid', '~> 2.3.7'
gem 'eventmachine', '1.0.3'
gem 'em-http-request', '~> 1.1.0'
gem 'em-synchrony', '~> 1.0.3'
gem 'resque', '~> 1.24.1'
gem 'resque-scheduler', '~> 2.0.1', :require => 'resque_scheduler'
gem 'resque-lock', '~> 1.1.0'
gem 'resque-loner', '~>1.2.1'
gem 'hiredis', '~>0.4.5'
gem 'em-hiredis', '~>0.2.1'
gem 'formtastic', '~>2.2.1'
gem 'cocoon', '~>1.0.22'
gem 'deep_cloneable', '~> 1.5.3'
gem 'redis-objects', '~>0.7.0',:require => 'redis/objects'
gem 'redis', '~> 3.0.4'
gem 'ar-octopus', :git => 'git://github.com/tchandy/octopus.git'
gem 'newrelic-redis'
gem 'sidekiq', '~> 2.13.0'
gem 'slim', '~>2.0.0'
gem 'sprockets', '~>2.2.1'
gem 'sinatra', '~>1.4.3'
gem 'mandrill-api', '~>1.0.37'
gem 'sidekiq-failures', '~> 0.2.1'
gem 'lograge', '~>0.2.0'
gem 'cancan', '~>1.6.10'
gem 'stripe', '~>1.8.4'

# Text -> HTML processors
gem 'redcarpet'

group :development, :test, :e2e do
  gem 'rspec'
  gem 'rspec-rails'
  gem 'hirb', '~>0.7.1'
  gem 'rspec-instafail', '~>0.2.4'
  gem 'pry'
  gem 'pry-debugger'
  gem 'jasmine'
  gem 'compass'
end

group :development do
  gem 'guard'
  gem 'guard-rspec'
  gem 'guard-spork'
  gem 'rb-fsevent'
  gem 'showoff-io'
  gem 'foreman'
  gem 'capistrano'
  gem 'capistrano_colors'
  gem 'capistrano-multiconfig'
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :test, :e2e do
  gem 'factory_girl_rails'
  gem 'shoulda'
  gem 'simplecov'
  gem 'spork-rails'
  gem 'database_cleaner'
  gem 'json_spec'
  gem 'capybara'
  gem 'launchy'
  gem 'timecop'
  gem 'webmock'
  gem 'capybara-webkit'
end
