# If you need to 'vendor your gems' for deploying your daemons, bundler is a
# great option. Update this Gemfile with any additional dependencies and run
# 'bundle install' to get them all installed. Daemon-kit's capistrano
# deployment will ensure that the bundle required by your daemon is properly
# installed.

source :gemcutter
source "http://gems.github.com"

# daemon-kit
gem 'daemon-kit'
gem 'rails'
gem 'activerecord'
gem 'mysql'
gem 'hpricot'
gem 'fastercsv'

# For more information on bundler, please visit http://gembundler.com
